version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build-and-publish:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run prod:build
      - run:
          name: Copy assets
          command: cp -R dist/* $CIRCLE_ARTIFACTS
      - run:
          name: Deploy
          command: >
            if [ $CIRCLE_BRANCH = 'master' ]; then aws s3 sync dist s3://fullstackbulletin.com && aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --invalidation-batch "{ \"Paths\": { \"Quantity\": 1, \"Items\": [ \"/*\" ] }, \"CallerReference\": \"CIRCLE-CI-BUILD-$CIRCLE_BUILD_NUM-$CIRCLE_SHA1\" }"; fi

workflows:
  build:
    jobs:
      - build-and-publish
